# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    wget https://sca-downloads.s3.amazonaws.com/cli/latest/ScaResolver-linux64.tar.gz
    tar -xzvf ScaResolver-linux64.tar.gz
    rm -rf ScaResolver-linux64.tar.gz 
    sudo apt install maven npm
  displayName: 'Run a multi-line script'

- task: Checkmarx AST@2
  inputs:
    CheckmarxService: 'What your service Connection is named'
    projectName: '$(Build.Repository.Name)'
    branchName: '$(Build.SourceBranchName)'
    tenantName: 'workshop'
    additionalParams: '--sca-resolver ./ScaResolver'

# see this documentation https://docs.checkmarx.com/en/34965-68725-using-sca-resolver-in-checkmarx-one-ci-cd-integrations.html

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
